### ISSUE TITLE
More documents

### ISSUE THREAD

**Issue by MadRatSRP** [nikita36078/J2ME_Docs#1]
https://github.com/mrRosset/Symbian-Archive/blob/master/SDKs-Docs.md
Вот ссылка и кроме этой ссылки весь этот репозиторий может тебе помочь. У тебя есть телеграм? мне удобнее будет писать по поводу нахождений доков туда

https://www.google.com/search?q=symbian+docs+github&oq=symbian+docs+github&aqs=chrome..69i57.6252j0j4&sourceid=chrome&ie=UTF-8
И отсюда тоже что-нибудь

**Comment by nikita36078** [comment]
Спасибо, посмотрю, что там есть полезного. Это всё-таки скорее материалы для нативных приложений симбиана (C/C+), чем для джавы. Телеграм есть, никнейм там тот же, что и здесь.
