### ISSUE TITLE
Новая дока (у тебя в списке не нашёл)

### ISSUE THREAD

**Issue by MadRatSRP** [nikita36078/J2ME_Docs#3]
https://docs.oracle.com/javame/config/cldc/ref-impl/midp2.0/jsr118/javax/microedition/lcdui/game/TiledLayer.html

**Comment by nikita36078** [comment]
Спасибо, но этот класс у меня есть - https://nikita36078.github.io/J2ME_Docs/docs/midp-2.0/javax/microedition/lcdui/game/TiledLayer.html
В MIDP 2.0 он лежит.
